### ISSUE TITLE
single and double floating-point numbers are confused

### ISSUE THREAD

**Issue by zjin-lcf** [UoB-HPC/BabelStream#98] opened 2021-05-12 22:06 UTC
~/BabelStream/build$ ./sycl-stream --float --device 2
BabelStream
Version: 3.4
Implementation: SYCL
Running kernels 100 times
Precision: float
Array size: 134.2 MB (=0.1 GB)
Total size: 402.7 MB (=0.4 GB)
Using SYCL device Intel(R) Iris(R) Xe Graphics 
terminate called after throwing an instance of 'cl::sycl::compile_program_error'
  what():  The program was built for 1 devices
Build program log for 'Intel(R) Iris(R) Xe Graphics':

error :double type is not supported on this platform
in kernel: 'typeinfo name for sycl_kernels::copy<double>'
error: backend compiler failed build.

Thanks

**Comment by tomdeakin** [comment] 2021-05-17 14:26
Thanks for reporting this. I had forgotten that support for FP64 on the device is optional in SYCL just as it is in OpenCL. In the OpenCL code, we have to check that the double version will work.

I've added a SYCL 1.2.1 solution to the current version of the code in #100 in the `issue-98` branch. Can you check if this works on your device please?

SYCL 2020 makes this check a bit nicer, so I'll update #77 with a similar check ready for when we merge that in.

**Comment by zjin-lcf** [comment] 2021-05-18 15:21
Sorry, the issue may not be really fixed.

./sycl-stream --float --device device_id
error :double type is not supported on this platform
in kernel: 'typeinfo name for sycl_kernels::init<double>'
error: backend compiler failed build.

error :double type is not supported on this platform
in kernel: 'typeinfo name for sycl_kernels::init<double>'
error: backend compiler failed build.

error :double type is not supported on this platform
in kernel: 'typeinfo name for sycl_kernels::init<double>'
error: backend compiler failed build.
 -11 (CL_BUILD_PROGRAM_FAILURE)
Aborted (core dumped)

**Comment by zjin-lcf** [comment] 2021-05-18 15:42
Sorry, I didn't check it before you closed the issue.

**Comment by tomdeakin** [comment] 2021-05-18 15:43
It auto-closed when I merged the PR, sorry!

**Comment by tomdeakin** [comment] 2021-05-18 16:05
Thanks for testing @zjin-lcf. I think the problem is now that both `float` and `double` have template instantiations (final two lines of `SYCLStream.cpp`, so both are being passed to the SYCL compiler at runtime. The compiler must be running before this code selects the device and exits if the feature is not supported.

I need to double check the SYCL specifications to find out if there is anything we can do in application code at compile time; but I suspect not.

**Comment by tomdeakin** [comment] 2021-05-18 16:11
@tom91136 also suggested that you could try to enable FP64 emulation on the DevCloud Xe GPUs with the following environment variables:
```
export OverrideDefaultFP64Settings=1 
export IGC_EnableDPEmulation=1
```
This should silence the compiler issues and run the `float` code. The `double` will probably run, just in emulated mode.

**Comment by zjin-lcf** [comment] 2021-05-18 22:00
Thank you for your suggestion. Please feel free to close the issue.

**Comment by tomdeakin** [comment] 2021-05-19 11:03
Issue #20 summarises the problems with the dot product kernel and single precision. There isn't a good solution that we've found.

**Comment by zjin-lcf** [comment] 2021-05-19 11:54
Okay. I assume that the error bounds are different for single precision and double precision.  People may just care about bandwidth for the benchmark, though.

**Comment by tomdeakin** [comment] 2021-05-19 13:20
Same error bounds (1.0E-8), but that might be a good way to account for the difference. I agree it's off-putting to have an error about correct values. I'll make a note in #20 with this suggestion. Thanks!

**Closed by tomdeakin** 2021-05-19 13:20 UTC
Labels: bug
